project:
  output-dir: _output
author: ""

lang: de

format:
  revealjs: 
    toc: true
    toc-depth: 1
    chalkboard:
      chalkEffect: 0.0
    slide-number: true
    logo: ../../images/BO-Logo_o_Wortmarke.png
    footer: Finite Elemente in der Baupraxis
    css: ["../../custom.css"]
  html:
    title-block-banner: "#888888"
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true

fig-format: png

jupyter: julia-1.10

bibliography: 
  - references.bib  
