project:
  output-dir: __output
author: ""

lang: de

format:
  revealjs: 
    toc: true
    toc-depth: 1
    chalkboard:
      chalkEffect: 0.0
    slide-number: true
    logo: ../../images/BO-Logo_o_Wortmarke.png
    footer: Finite Elemente in der Baupraxis
    css:
    - custom.css
    theme: 
    - style-slides.scss
    - style-titlepage.scss
  html:
    title-block-banner: "#888888"
    number-sections: true
    number-depth: 2
  pdf:
    number-sections: true

fig-format: png

bibliography: 
  - references.bib  
