name: Render and publish

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write      
    steps:
      - name: Check out
        uses: actions/checkout@v5

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: "Render"
        run: |
          make qmd

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '__output'

  deploy:
    needs: render
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:    
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

